### ISSUE TITLE
AndroidSteering not working with vJoy / Forza Horizon 5

### ISSUE THREAD

**Issue by miskla** [teamclouday/AndroidSteering#5]
Hello, first of all thanks a lot for this project, it's nice that this exists.

I tried installing AndroidSteering to use my phone as a steering wheel for Forza Horizon 5:

* I installed vJoy with your recommended settings
* I installed the Windows app, with my computer connected with Wifi (ethernet didn't work and showed server ip 127.0.0.1), and started the app (listening)
* I installed the Android app (Wifi to the same router) and connected to the server. The server correctly shows the client connecting, with the client's ip displayed.

So it looks like everything is properly connected, but I'm not sure how to use the buttons or the steering in-game.
I have tried the three modes, steering (default) / (alternative) / gamepad.
Nothing happens on my computer when I press the buttons in the Wheel app on Android.
I tried to customize the commands in Forza, but I don't see anything happening here either when I press the buttons on Wheel.
I also tried going into the game controller settings in Windows, where the vJoy device is correctly listed.
There is a tab to test the device, but again nothing happens when I press the buttons on Wheel.

By the way, what is the Configure button for in the Windows app? This opens a gamepad, but nothing happens when I press the buttons.

Thank you for your help!

**Comment by teamclouday** [comment]
Hi, thanks for trying this app!\
From your description, I guess it is because the Windows app didn't talk to the vJoy driver correctly. It happened to me sometimes, and I had to re-open the app. Or it is the firewall that is blocking this app from connecting within the private network. (appears connected but actually blocked)

You can probably verify this by setting up the connection and open "Monitor vJoy" app (installed together with vJoy driver). If you move the phone but nothing changes on the monitor, then this is the issue.

Another possible reason is that the Horizon game does not understand the gamepad mapping of vJoy. If you are on Steam, you can click "Configure" button in the Windows app and map buttons/axes in Stream controller settings. Then Horizon can use this mapping as a xbox controller. Otherwise you may have to map the buttons/axes in the game, but I assume most games have xbox controller preset.

And yes, I need to work on the Windows app so that the use of a vJoy device is stable enough. I've also updated the app a few weeks ago and included features such as selecting an ethernet adapter, but currently there is a huge latency issue in the published release build.\
After I figure that out, I should be able to release a new version of this app with improved stability.

**Comment by miskla** [comment]
Thanks a lot for your quick answer.
Monitor vJoy actually showed changes when I used my phone, so I went back to Horizon game settings, and I was trying to change the wrong controller settings (gamepad instead of wheel).
Going to the wheel tab, I was able to map the buttons correctly.
Then there is a Forza related issue where there's a bug when saving the wheel settings ("Active controller must be a wheel" error message), but in the end I was able to save using keyboard/mouse.

So it works, thanks!
